__author__ = 'Konstantin Glazyrin'

# pytango related names
READ_ATTRIBUTE = "READ_ATTRIBUTE"
WRITE_ATTRIBUTE = "WRITE_ATTRIBUTE"
WRITE_ATTRIBUTE_ASYNCH = "WRITE_ATTRIBUTE_ASYNCH"
COMMAND_INOUT = "COMMAND_INOUT"
COMMAND_INOUT_ASYNCH = "COMMAND_INOUT_ASYNCH"
WAIT_FOR_STATE = "WAIT_FOR_STATE"

# time functions related
TIMESTAMP = "TIMESTAMP"
DATE_AND_TIME = "DATE_AND_TIME"
