__author__ = 'Konstantin Glazyrin'

PROFILE_DIR = "PROFILE_DIR"
PROFILE_PRIORITY = "PROFILE_PRIORITY"
PROFILE_DIRREPORTS = "PROFILE_DIRREPORTS"
PROFILE_DIRSAVEDPROFILES = "PROFILE_DIRSAVEDPROFILES"

PROFILE_NAME = "PROFILE_NAME"
PROFILE_NICKNAME = "PROFILE_NICKNAME"
PROFILE_START = "PROFILE_START"
PROFILE_CMDLOOP = "PROFILE_CMDLOOP"
PROFILE_CMDINIT = "PROFILE_CMDINIT"
PROFILE_DELAY = "PROFILE_DELAY"
PROFILE_PREPROGRAMMED = "PROFILE_PREPROGRAMMED"

PROFILE_OFFSETS = "PROFILE_OFFSETS"
PROFILE_DEFAULTOFFSET = "PROFILE_DEFAULTOFFSET"

PROFILE_A = "A"
PROFILE_B = "B"
PROFILE_C = "C"
PROFILE_D = "D"

PROFILE_HTML = "PROFILE_HTML"

CMD = "cmd"
NICK = "nick-name"
DESC = "description"
DATA = "data"
CENTER="CENTER"
FWHMX = "FWHMX"
FWHMY = "FWHMY"
ROI_VIEWDATA = "ROI_VIEWDATA"
ROI_FITDATA = "ROI_FITDATA"

ROI_FITFWHMX = "ROI_FITFWHMX"
ROI_FITFWHMY = "ROI_FITFWHMY"
ROI_FITCOMS = "ROI_FITCOMS"

WIDTH = "WIDTH"
IMAGES = "IMAGES"
HEIGHT = "HEIGHT"
DATASTR = "datastr"
FORMAT = "format"
ARGS = "ARGS"
TYPE="type"
SHOWHIDE = "SHOWHIDE"
DEFCH = "DEFCH"
SEPARATOR = "SEPARATOR"

ROI_VIEW = "ROI_VIEW"
ROI_FIT = "ROI_FIT"

PROFILE_SPLITTER_TYPE = "PROFILE_SPLITTER_TYPE"
PROFILE_SPLITTER_POS = "PROFILE_SPLITTER_POS"

PROFILE_CONTROLLERS = "PROFILE_CONTROLLERS"

PROFILE_CODEC = "PROFILE_CODEC"

PROFILE_TANGOATTR = "PROFILE_TANGOATTR"

PROFILE_ROIVIEW = "PROFILE_ROIVIEW"
PROFILE_ROIFIT = "PROFILE_ROIFIT"

PROFILE_SHOW_ROIVIEW = "PROFILE_SHOW_ROIVIEW"
PROFILE_SHOW_ROIFIT = "PROFILE_SHOW_ROIFIT"

PROFILE_INSERT_RECT = "PROFILE_INSERT_RECT"

PROFILE_INSERTVIEW_LINES = "PROFILE_INSERTVIEW_LINES"
PROFILE_INSERTCENTER_LINES = "PROFILE_INSERTCENTER_LINES"

PROFILE_COLORTABLE = "PROFILE_COLORTABLE"

PENFIT = "PENFIT"
PENVIEW = "PENVIEW"